const mockList = {
  results: [
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Ben',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '1/1/1',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Dasha',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '2/2/2',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Pasha',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '2/2/2',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Ben',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '1/1/1',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Dasha',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '2/2/2',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Ben',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '1/1/1',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Dasha',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '2/2/2',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Ben',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '1/1/1',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Dasha',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '2/2/2',
      vehicles: [],
    },
    {
      birth_year: '132',
      created: new Date(),
      edited: new Date(),
      eye_color: 'red',
      films: [],
      gender: 'Male',
      hair_color: 'brown',
      height: '182',
      homeworld: 'Earth',
      mass: '64',
      name: 'Ben',
      skin_color: 'green',
      species: [],
      starships: [],
      url: '1/1/1',
      vehicles: [],
    },
  ],
  count: 23,
  meta: {
    status: 200,
    msg: 'OK',
    response_id: '21333',
  },
};

const mockCard = {
  birth_year: '132',
  created: new Date(),
  edited: new Date(),
  eye_color: 'red',
  films: [],
  gender: 'Male',
  hair_color: 'brown',
  height: '182',
  homeworld: 'Earth',
  mass: '64',
  name: 'Ben',
  skin_color: 'green',
  species: [],
  starships: [],
  url: '2/2/2',
  vehicles: [],
};

export { mockList, mockCard };
